import type { Agent, Task, Project, Engagement, Resource, Workflow } from "./types"

export const mockAgents: Agent[] = [
  {
    id: "agent-1",
    name: "Architect Agent",
    type: "architect",
    status: "working",
    currentTask: "bd-a3f8.2",
    skills: ["System Design", "Cloud Architecture", "Security"],
    utilization: 85,
    completedTasks: 47,
    avatar: "/robot-architect-blue.jpg",
  },
  {
    id: "agent-2",
    name: "Developer Agent",
    type: "developer",
    status: "working",
    currentTask: "bd-b2c1.1",
    skills: ["TypeScript", "React", "Node.js", "Python"],
    utilization: 92,
    completedTasks: 156,
    avatar: "/robot-developer-green.jpg",
  },
  {
    id: "agent-3",
    name: "Analysis Agent",
    type: "analyst",
    status: "idle",
    skills: ["Data Analysis", "Requirements", "Documentation"],
    utilization: 45,
    completedTasks: 89,
    avatar: "/robot-analyst-purple.jpg",
  },
  {
    id: "agent-4",
    name: "Test Agent",
    type: "tester",
    status: "working",
    currentTask: "bd-c4d2.3",
    skills: ["Unit Testing", "E2E Testing", "Performance"],
    utilization: 78,
    completedTasks: 234,
    avatar: "/robot-tester-orange.jpg",
  },
  {
    id: "agent-5",
    name: "Review Agent",
    type: "reviewer",
    status: "blocked",
    currentTask: "bd-d5e3.1",
    skills: ["Code Review", "Security Audit", "Best Practices"],
    utilization: 62,
    completedTasks: 178,
    avatar: "/robot-reviewer-cyan.jpg",
  },
]

export const mockTasks: Task[] = [
  {
    id: "bd-a3f8",
    title: "Cloud Migration Epic",
    description: "Migrate legacy systems to AWS cloud infrastructure",
    type: "epic",
    priority: 0,
    status: "in_progress",
    labels: ["cloud", "infrastructure", "migration"],
    dependencies: [],
    createdAt: "2025-12-01T10:00:00Z",
    updatedAt: "2025-01-04T15:30:00Z",
    estimatedHours: 480,
    actualHours: 220,
    projectId: "proj-1",
  },
  {
    id: "bd-a3f8.1",
    title: "Infrastructure Assessment",
    description: "Assess current infrastructure and create migration plan",
    type: "task",
    priority: 1,
    status: "completed",
    assignee: "agent-1",
    labels: ["assessment", "planning"],
    dependencies: [{ type: "parent-child", targetId: "bd-a3f8" }],
    createdAt: "2025-12-01T10:00:00Z",
    updatedAt: "2025-12-15T14:00:00Z",
    estimatedHours: 40,
    actualHours: 38,
    projectId: "proj-1",
  },
  {
    id: "bd-a3f8.2",
    title: "Design Cloud Architecture",
    description: "Design target state AWS architecture",
    type: "task",
    priority: 1,
    status: "in_progress",
    assignee: "agent-1",
    labels: ["architecture", "aws"],
    dependencies: [
      { type: "parent-child", targetId: "bd-a3f8" },
      { type: "blocks", targetId: "bd-a3f8.1" },
    ],
    createdAt: "2025-12-16T10:00:00Z",
    updatedAt: "2025-01-04T15:30:00Z",
    estimatedHours: 80,
    actualHours: 45,
    projectId: "proj-1",
  },
  {
    id: "bd-b2c1",
    title: "API Integration Platform",
    description: "Build unified API integration layer for client systems",
    type: "epic",
    priority: 1,
    status: "in_progress",
    labels: ["api", "integration"],
    dependencies: [],
    createdAt: "2025-11-15T09:00:00Z",
    updatedAt: "2025-01-03T11:00:00Z",
    estimatedHours: 320,
    actualHours: 180,
    projectId: "proj-2",
  },
  {
    id: "bd-b2c1.1",
    title: "Implement REST Gateway",
    description: "Build REST API gateway with rate limiting and auth",
    type: "feature",
    priority: 1,
    status: "in_progress",
    assignee: "agent-2",
    labels: ["api", "gateway"],
    dependencies: [{ type: "parent-child", targetId: "bd-b2c1" }],
    createdAt: "2025-11-20T10:00:00Z",
    updatedAt: "2025-01-04T09:00:00Z",
    estimatedHours: 60,
    actualHours: 35,
    projectId: "proj-2",
  },
  {
    id: "bd-c4d2",
    title: "Security Compliance Audit",
    description: "Comprehensive security audit for SOC2 compliance",
    type: "epic",
    priority: 0,
    status: "in_progress",
    labels: ["security", "compliance", "soc2"],
    dependencies: [],
    createdAt: "2025-12-20T10:00:00Z",
    updatedAt: "2025-01-04T12:00:00Z",
    estimatedHours: 160,
    actualHours: 60,
    projectId: "proj-3",
  },
  {
    id: "bd-c4d2.3",
    title: "Penetration Testing",
    description: "Execute penetration tests on all public endpoints",
    type: "task",
    priority: 0,
    status: "in_progress",
    assignee: "agent-4",
    labels: ["security", "testing"],
    dependencies: [{ type: "parent-child", targetId: "bd-c4d2" }],
    createdAt: "2025-12-28T10:00:00Z",
    updatedAt: "2025-01-04T14:00:00Z",
    estimatedHours: 24,
    actualHours: 12,
    projectId: "proj-3",
  },
  {
    id: "bd-d5e3",
    title: "Data Analytics Dashboard",
    description: "Build executive analytics dashboard",
    type: "epic",
    priority: 2,
    status: "open",
    labels: ["analytics", "dashboard"],
    dependencies: [],
    createdAt: "2026-01-02T10:00:00Z",
    updatedAt: "2026-01-02T10:00:00Z",
    estimatedHours: 200,
    projectId: "proj-4",
  },
  {
    id: "bd-d5e3.1",
    title: "Review Dashboard Requirements",
    description: "Review and approve dashboard specifications",
    type: "task",
    priority: 2,
    status: "blocked",
    assignee: "agent-5",
    labels: ["review", "requirements"],
    dependencies: [
      { type: "parent-child", targetId: "bd-d5e3" },
      { type: "blocks", targetId: "bd-b2c1" },
    ],
    createdAt: "2026-01-03T10:00:00Z",
    updatedAt: "2026-01-04T10:00:00Z",
    estimatedHours: 8,
    projectId: "proj-4",
  },
]

export const mockProjects: Project[] = [
  {
    id: "proj-1",
    name: "Acme Cloud Migration",
    client: "Acme Corporation",
    status: "active",
    progress: 46,
    startDate: "2025-12-01",
    endDate: "2026-03-31",
    budget: 450000,
    spent: 185000,
    team: ["agent-1", "agent-2"],
    tasks: 24,
    completedTasks: 11,
  },
  {
    id: "proj-2",
    name: "GlobalBank API Platform",
    client: "Global Bank Inc.",
    status: "active",
    progress: 56,
    startDate: "2025-11-15",
    endDate: "2026-02-28",
    budget: 320000,
    spent: 180000,
    team: ["agent-2", "agent-4"],
    tasks: 18,
    completedTasks: 10,
  },
  {
    id: "proj-3",
    name: "MediCare SOC2 Compliance",
    client: "MediCare Systems",
    status: "active",
    progress: 38,
    startDate: "2025-12-20",
    endDate: "2026-02-15",
    budget: 180000,
    spent: 62000,
    team: ["agent-4", "agent-5"],
    tasks: 12,
    completedTasks: 4,
  },
  {
    id: "proj-4",
    name: "RetailMax Analytics",
    client: "RetailMax Corp",
    status: "planning",
    progress: 5,
    startDate: "2026-01-15",
    endDate: "2026-04-30",
    budget: 280000,
    spent: 12000,
    team: ["agent-3", "agent-5"],
    tasks: 8,
    completedTasks: 0,
  },
]

export const mockEngagements: Engagement[] = [
  {
    id: "eng-1",
    name: "Digital Transformation Initiative",
    client: "Acme Corporation",
    type: "implementation",
    status: "active",
    value: 1200000,
    startDate: "2025-10-01",
    projects: ["proj-1"],
  },
  {
    id: "eng-2",
    name: "Financial Services Modernization",
    client: "Global Bank Inc.",
    type: "consulting",
    status: "active",
    value: 850000,
    startDate: "2025-11-01",
    projects: ["proj-2"],
  },
  {
    id: "eng-3",
    name: "Healthcare Compliance Program",
    client: "MediCare Systems",
    type: "managed-services",
    status: "active",
    value: 420000,
    startDate: "2025-12-01",
    projects: ["proj-3"],
  },
]

export const mockResources: Resource[] = [
  {
    id: "res-1",
    name: "Sarah Chen",
    role: "Solutions Architect",
    department: "Cloud Services",
    skills: ["AWS", "Azure", "Kubernetes", "Terraform"],
    availability: 60,
    currentProjects: ["proj-1"],
    hourlyRate: 250,
    avatar: "/woman-professional-architect.jpg",
  },
  {
    id: "res-2",
    name: "Marcus Johnson",
    role: "Senior Developer",
    department: "Engineering",
    skills: ["TypeScript", "Python", "Go", "React"],
    availability: 40,
    currentProjects: ["proj-1", "proj-2"],
    hourlyRate: 200,
    avatar: "/man-professional-developer.jpg",
  },
  {
    id: "res-3",
    name: "Emily Rodriguez",
    role: "Security Consultant",
    department: "Security",
    skills: ["Penetration Testing", "SOC2", "GDPR", "ISO27001"],
    availability: 80,
    currentProjects: ["proj-3"],
    hourlyRate: 275,
    avatar: "/woman-professional-security.jpg",
  },
  {
    id: "res-4",
    name: "David Kim",
    role: "Data Engineer",
    department: "Analytics",
    skills: ["Spark", "Airflow", "dbt", "Snowflake"],
    availability: 100,
    currentProjects: [],
    hourlyRate: 185,
    avatar: "/man-professional-data-engineer.jpg",
  },
]

export const mockWorkflows: Workflow[] = [
  {
    id: "wf-1",
    name: "Cloud Migration Pipeline",
    description: "End-to-end workflow for cloud migration projects",
    status: "active",
    projectId: "proj-1",
    createdAt: "2025-12-01T10:00:00Z",
    steps: [
      {
        id: "step-1",
        name: "Discovery & Assessment",
        type: "agent",
        status: "completed",
        agentId: "agent-3",
        dependencies: [],
        outputs: ["assessment-report", "inventory-list"],
      },
      {
        id: "step-2",
        name: "Architecture Design",
        type: "agent",
        status: "active",
        agentId: "agent-1",
        dependencies: ["step-1"],
        outputs: ["architecture-diagram", "migration-plan"],
      },
      {
        id: "step-3",
        name: "Stakeholder Approval",
        type: "approval",
        status: "pending",
        assignee: "res-1",
        dependencies: ["step-2"],
        outputs: ["approval-record"],
      },
      {
        id: "step-4",
        name: "Infrastructure Provisioning",
        type: "agent",
        status: "pending",
        agentId: "agent-2",
        dependencies: ["step-3"],
        outputs: ["terraform-state", "resource-manifest"],
      },
      {
        id: "step-5",
        name: "Data Migration",
        type: "agent",
        status: "pending",
        agentId: "agent-2",
        dependencies: ["step-4"],
        outputs: ["migration-logs", "validation-report"],
      },
      {
        id: "step-6",
        name: "Testing & Validation",
        type: "agent",
        status: "pending",
        agentId: "agent-4",
        dependencies: ["step-5"],
        outputs: ["test-results", "performance-report"],
      },
      {
        id: "step-7",
        name: "Final Review",
        type: "human",
        status: "pending",
        assignee: "res-1",
        dependencies: ["step-6"],
        outputs: ["signoff-document"],
      },
    ],
  },
]
